# Generated by Django 3.0.3 on 2020-02-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choce_text',
            new_name='choice_text',
        ),
    ]
